CREATE TABLE `kao_attendanceshift` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(255) DEFAULT NULL COMMENT '班次名称',
  `typelist` enum('0','1') NOT NULL DEFAULT '0' COMMENT '考勤类型:0=固定班次(每天考勤时间一样),1=弹性班次(按照排版自定义考勤时间)',
  `worktime` int(10) DEFAULT NULL COMMENT '工作时间',
  `starttime` int(10) NOT NULL COMMENT '开始工作时间',
  `endtime` int(10) NOT NULL COMMENT '结束工作时间',
  `startbefore` int(5) DEFAULT NULL COMMENT '最早打卡时间(提前多少分钟)',
  `endbefore` int(5) DEFAULT NULL COMMENT '最晚打卡时间(延后多少分钟)',
  `typedata` enum('0','1') DEFAULT '0' COMMENT '抽查时间与工作时间是否保持一致:0=否,1=是',
  `reststarttime` int(10) DEFAULT NULL COMMENT '休息开始时间',
  `restendtime` int(10) DEFAULT NULL COMMENT '休息结束时间',
  `startmiss` int(5) DEFAULT NULL COMMENT '迟到多少时间打卡不算迟到',
  `endmiss` int(5) DEFAULT NULL COMMENT '早退多少时间打卡不算早退',
  `startbelate` int(5) DEFAULT NULL COMMENT '迟到多少时间打卡视为缺勤',
  `endlate` int(5) DEFAULT NULL COMMENT '早退多少时间打卡视为早退',
  `timedraw` int(5) DEFAULT NULL COMMENT '抽查打卡多少超过多少时间算缺勤',
  `createtime` int(10) DEFAULT NULL COMMENT '创建时间',
  `updatetime` int(10) DEFAULT NULL COMMENT '修改时间',
  `onestarttime` int(10) DEFAULT NULL COMMENT '第一轮抽卡开始时间',
  `oneendtime` int(10) DEFAULT NULL COMMENT '第一轮抽卡结束时间',
  `onechou` int(5) DEFAULT '0' COMMENT '第一轮 抽卡次数',
  `twostarttime` int(10) DEFAULT NULL COMMENT '第二轮抽卡开始时间',
  `twoendtime` int(10) DEFAULT NULL COMMENT '第二轮抽卡结束时间',
  `twochou` int(5) DEFAULT '0' COMMENT '第二轮 抽卡次数',
  `threestarttime` int(10) DEFAULT NULL COMMENT '第三轮抽卡开始时间',
  `threeendtime` int(10) DEFAULT NULL COMMENT '第三轮抽卡结束时间',
  `threechou` int(5) DEFAULT '0' COMMENT '第三轮 抽卡次数',
  `fourstarttime` int(10) DEFAULT NULL COMMENT '第四轮抽卡开始时间',
  `fourendtime` int(10) DEFAULT NULL COMMENT '第四轮抽卡结束时间',
  `fourchou` int(5) DEFAULT '0' COMMENT '第四轮 抽卡次数',
  `isadvance` int(5) DEFAULT NULL COMMENT '提前多少分钟推送通知',
  `choukajian` int(5) DEFAULT NULL COMMENT '每轮抽卡间隔至少多少分钟',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='考勤班次';
