name: CI Demo

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      # ✅ 只做语法检查
      - name: PHP Syntax Check
        run: php -l index.php

      # ✅ 构建镜像
      - name: Build Docker Image
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t angel-demo:${SHORT_SHA} .

      # ✅ 登录 Docker Hub
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ✅ 推送镜像
      - name: Push Image
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)

          docker tag angel-demo:${SHORT_SHA} ${{ secrets.DOCKER_USERNAME }}/angel-demo:${SHORT_SHA}
          docker tag angel-demo:${SHORT_SHA} ${{ secrets.DOCKER_USERNAME }}/angel-demo:latest

          docker push ${{ secrets.DOCKER_USERNAME }}/angel-demo:${SHORT_SHA}
          docker push ${{ secrets.DOCKER_USERNAME }}/angel-demo:latest